 <option value="SPREF391">ADDIS-ABEBA</option>
<option value="SPREF024">ABENGOUROU</option>
<option value="SPREF372">ABIDJAN</option>
<option value="SPREF440">ABIGUI</option>
<option value="SPREF038">ABOISSO</option>
<option value="SPREF155">ABOISSO COMOE</option>
<option value="SPREF161">ABONGOUA</option>
<option value="SPREF407">ABUJA</option>
<option value="SPREF394">ACCRA</option>
<option value="SPREF039">ADAOU</option>
<option value="SPREF046">ADIAKE</option>
<option value="SPREF040">ADJOUAN</option>
<option value="SPREF147">ADZOPE</option>
<option value="SPREF158">AFFERY</option>
<option value="SPREF131">AGBOVILLE</option>
<option value="SPREF031">AGNIBILEKRO</option>
<option value="SPREF148">AGOU</option>
<option value="SPREF169">AHOUANOU</option>
<option value="SPREF034">AKOBOISSUE</option>
<option value="SPREF157">AKOUPE</option>
<option value="SPREF153">ALEPE</option>
<option value="SPREF373">ALGER</option>
<option value="SPREF441">ALLOSSO</option>
<option value="SPREF362">AMANVI</option>
<option value="SPREF025">AMELEKIA</option>
<option value="SPREF097">ANANDA</option>
<option value="SPREF117">ANDE</option>
<option value="SPREF302">ANDO KEKRENOU</option>
<option value="SPREF125">ANGONDA</option>
<option value="SPREF026">ANIASSUE</option>
<option value="SPREF150">ANNEPE</option>
<option value="SPREF112">ANOUMABA</option>
<option value="SPREF364">ANYAMA</option>
<option value="SPREF345">APPIMANDOUM</option>
<option value="SPREF295">ARIKOKAKA</option>
<option value="SPREF114">ARRAH</option>
<option value="SPREF480">ASSAHARA</option>
<option value="SPREF482">ASSIE-KOUMASSI</option>
<option value="SPREF149">ASSIKOI</option>
<option value="SPREF048">ASSINIE MAFIA</option>
<option value="SPREF360">ASSUEFRY</option>
<option value="SPREF167">ATOUTOU A</option>
<option value="SPREF370">ATTIEGOUAKRO</option>
<option value="SPREF041">AYAME</option>
<option value="SPREF307">AYAOU SRAN</option>
<option value="SPREF137">AZAGUIE</option>
<option value="SPREF171">BACANDA</option>
<option value="SPREF291">BADIKAHA</option>
<option value="SPREF206">BAGOHOUO</option>
<option value="SPREF462">BAHOUAKAHA</option>
<option value="SPREF062">BAKO</option>
<option value="SPREF201">BAKOUBLY</option>
<option value="SPREF404">BAMAKO</option>
<option value="SPREF478">BANDAKAGNI</option>
<option value="SPREF207">BANGOLO</option>
<option value="SPREF450">BANNEU</option>
<option value="SPREF285">BASSAWA</option>
<option value="SPREF463">BAYA</option>
<option value="SPREF079">BAYOTA</option>
<option value="SPREF242">BAZRE</option>
<option value="SPREF151">BECEDI BRIGNAN</option>
<option value="SPREF159">BECOUEFIN</option>
<option value="SPREF224">BEDIALA</option>
<option value="SPREF108">BENGASSOU</option>
<option value="SPREF303">BEOUMI</option>
<option value="SPREF374">BERLIN</option>
<option value="SPREF413">BERNE</option>
<option value="SPREF036">BETTIE</option>
<option value="SPREF181">BIANKOUMA</option>
<option value="SPREF042">BIANOUAN</option>
<option value="SPREF162">BIEBY</option>
<option value="SPREF467">BILIMONO</option>
<option value="SPREF180">BIN HOUYE</option>
<option value="SPREF143">BINAO BOUSSOUE</option>
<option value="SPREF367">BINGERVILLE</option>
<option value="SPREF186">BLAPLEU</option>
<option value="SPREF212">BLENIMEOUIN</option>
<option value="SPREF279">BLESSEGUE</option>
<option value="SPREF194">BLOLEQUIN</option>
<option value="SPREF355">BOAHIA</option>
<option value="SPREF469">BOBI</option>
<option value="SPREF106">BOCANDA</option>
<option value="SPREF304">BODOKRO</option>
<option value="SPREF175">BOGOUINE</option>
<option value="SPREF230">BOGUEDIA</option>
<option value="SPREF437">BOLI</option>
<option value="SPREF343">BONDO</option>
<option value="SPREF342">BONDOUKOU</option>
<option value="SPREF051">BONGO</option>
<option value="SPREF116">BONGOUANOU</option>
<option value="SPREF100">BONGUERA</option>
<option value="SPREF286">BONIEREDOUGOU</option>
<option value="SPREF436">BONIKRO</option>
<option value="SPREF240">BONON</option>
<option value="SPREF050">BONOUA</option>
<option value="SPREF323">BOOKO</option>
<option value="SPREF259">BORON</option>
<option value="SPREF322">BOROTOU</option>
<option value="SPREF299">BOTRO</option>
<option value="SPREF238">BOUAFLE</option>
<option value="SPREF296">BOUAKE</option>
<option value="SPREF310">BOUANDOUGOU</option>
<option value="SPREF477">BOUGOU</option>
<option value="SPREF431">BOUGOUSSO</option>
<option value="SPREF335">BOUNA</option>
<option value="SPREF269">BOUNDIALI</option>
<option value="SPREF380">BRASILIA</option>
<option value="SPREF297">BROBO</option>
<option value="SPREF365">BROFODOUME</option>
<option value="SPREF379">BRUXELLES</option>
<option value="SPREF003">BUYO</option>
<option value="SPREF132">CECHI</option>
<option value="SPREF395">CONAKRY</option>
<option value="SPREF386">COPENHAGUE</option>
<option value="SPREF284">DABAKALA</option>
<option value="SPREF163">DABOU</option>
<option value="SPREF009">DABOUYO</option>
<option value="SPREF435">DAIRO-DIDOZO</option>
<option value="SPREF412">DAKAR</option>
<option value="SPREF020">DAKPADOU</option>
<option value="SPREF447">DALEU</option>
<option value="SPREF220">DALOA</option>
<option value="SPREF033">DAME</option>
<option value="SPREF188">DANANE</option>
<option value="SPREF156">DANGUIRA</option>
<option value="SPREF233">DANIA</option>
<option value="SPREF095">DAOUKRO</option>
<option value="SPREF275">DEBETE</option>
<option value="SPREF301">DIABO</option>
<option value="SPREF037">DIAMARAKRO</option>
<option value="SPREF474">DIAMBA</option>
<option value="SPREF311">DIANRA</option>
<option value="SPREF312">DIANRA VILLAGE</option>
<option value="SPREF470">DIARABANA</option>
<option value="SPREF266">DIAWALA </option>
<option value="SPREF128">DIDIEVI</option>
<option value="SPREF087">DIDOKO</option>
<option value="SPREF083">DIEGONEFLA</option>
<option value="SPREF210">DIEOUZON</option>
<option value="SPREF075">DIGNAGO</option>
<option value="SPREF258">DIKODOUGOU</option>
<option value="SPREF353">DIMANDOUGOU</option>
<option value="SPREF104">DIMBOKRO</option>
<option value="SPREF067">DIOULATIEDOUGOU</option>
<option value="SPREF084">DIVO</option>
<option value="SPREF298">DJEBONOUA</option>
<option value="SPREF377">DJEDDAH</option>
<option value="SPREF127">DJEKANOU</option>
<option value="SPREF333">DJIBROSSO</option>
<option value="SPREF016">DJOUROUTOU</option>
<option value="SPREF012">DOBA</option>
<option value="SPREF013">DOGBO</option>
<option value="SPREF195">DOKE</option>
<option value="SPREF336">DOROPO</option>
<option value="SPREF327">DUALLA</option>
<option value="SPREF202">DUEKOUE</option>
<option value="SPREF032">DUFFREBO</option>
<option value="SPREF027">EBILASSOKRO</option>
<option value="SPREF170">EBOUNOU</option>
<option value="SPREF421">ETRANGER</option>
<option value="SPREF096">ETTROKRO</option>
<option value="SPREF047">ETUEBOUE</option>
<option value="SPREF215">FACOBLY</option>
<option value="SPREF334">FADIADOUGOU</option>
<option value="SPREF102">FAMIENKRO</option>
<option value="SPREF432">FENGOLO</option>
<option value="SPREF261">FERKESSEDOUGOU</option>
<option value="SPREF287">FOUMBOLO</option>
<option value="SPREF320">FOUNGBESSO</option>
<option value="SPREF022">FRESCO</option>
<option value="SPREF282">FRONAN</option>
<option value="SPREF014">GABIADJI</option>
<option value="SPREF221">GADOUAN</option>
<option value="SPREF072">GAGNOA</option>
<option value="SPREF434">GAGORE</option>
<option value="SPREF076">GALEBRE</option>
<option value="SPREF271">GANAONI</option>
<option value="SPREF023">GBAGBAM</option>
<option value="SPREF182">GBANGBEGOUINE</option>
<option value="SPREF177">GBANGBEGOUINE YATI</option>
<option value="SPREF205">GBAPLEU</option>
<option value="SPREF066">GBELEBAN</option>
<option value="SPREF223">GBOGUHE</option>
<option value="SPREF487">GBOLOUVILLE</option>
<option value="SPREF277">GBON</option>
<option value="SPREF449">GBON-HOUYE</option>
<option value="SPREF187">GBONNE</option>
<option value="SPREF414">GENEVE</option>
<option value="SPREF078">GNANGBODOUGNAO</option>
<option value="SPREF246">GOHITAFLA</option>
<option value="SPREF213">GOHOUO ZAGNA</option>
<option value="SPREF146">GOMON</option>
<option value="SPREF225">GONATE</option>
<option value="SPREF091">GOUDOUKO</option>
<option value="SPREF445">GOUINE</option>
<option value="SPREF451">GOULALEU</option>
<option value="SPREF059">GOULIA</option>
<option value="SPREF344">GOUMERE</option>
<option value="SPREF017">GRABO</option>
<option value="SPREF049">GRAND BASSAM</option>
<option value="SPREF011">GRAND BEREBY</option>
<option value="SPREF168">GRAND LAHOU</option>
<option value="SPREF135">GRAND MORIE</option>
<option value="SPREF002">GRAND ZATTRY</option>
<option value="SPREF236">GREGBEU</option>
<option value="SPREF203">GUEHIEBLY</option>
<option value="SPREF082">GUEPAHOUO</option>
<option value="SPREF237">GUESSABO</option>
<option value="SPREF138">GUESSIGUIE</option>
<option value="SPREF008">GUEYO</option>
<option value="SPREF204">GUEZON</option>
<option value="SPREF453">GUEZON (FACOBLY)</option>
<option value="SPREF073">GUIBEROUA</option>
<option value="SPREF260">GUIEMBE</option>
<option value="SPREF191">GUIGLO</option>
<option value="SPREF211">GUINGLO TAHOUAKE</option>
<option value="SPREF319">GUINTEGUELA</option>
<option value="SPREF092">GUITRY</option>
<option value="SPREF085">HIRE</option>
<option value="SPREF231">IBOGUHE</option>
<option value="SPREF226">ISSIA</option>
<option value="SPREF166">JACQUEVILLE</option>
<option value="SPREF452">KAADE</option>
<option value="SPREF461">KAGBOLODOUGOU</option>
<option value="SPREF274">KANAKONO</option>
<option value="SPREF331">KANI</option>
<option value="SPREF058">KANIASSO</option>
<option value="SPREF250">KANOROBA</option>
<option value="SPREF486">KAOUARA</option>
<option value="SPREF251">KARAKORO </option>
<option value="SPREF270">KASSERE</option>
<option value="SPREF476">KATIALI</option>
<option value="SPREF281">KATIOLA</option>
<option value="SPREF475">KATOGO</option>
<option value="SPREF433">KIMIRILA SUD</option>
<option value="SPREF408">KINSHASA</option>
<option value="SPREF103">KOFFI AMONKRO</option>
<option value="SPREF473">KOKOMIAN</option>
<option value="SPREF124">KOKOUMBO</option>
<option value="SPREF278">KOLIA</option>
<option value="SPREF254">KOMBORODOUGOU</option>
<option value="SPREF305">KONDROBO</option>
<option value="SPREF262">KONG</option>
<option value="SPREF317">KONGASSO</option>
<option value="SPREF458">KONI</option>
<option value="SPREF244">KONONFLA</option>
<option value="SPREF325">KOONAN</option>
<option value="SPREF248">KORHOGO</option>
<option value="SPREF321">KORO</option>
<option value="SPREF369">KOSSOU</option>
<option value="SPREF481">KOTOBI</option>
<option value="SPREF338">KOTOUBA</option>
<option value="SPREF109">KOUADIOBLEKRO</option>
<option value="SPREF044">KOUAKRO</option>
<option value="SPREF190">KOUAN HOULE</option>
<option value="SPREF356">KOUASSI DATEKRO</option>
<option value="SPREF107">KOUASSI-KOUASSIKRO</option>
<option value="SPREF243">KOUETINFLA</option>
<option value="SPREF214">KOUIBLY</option>
<option value="SPREF263">KOUMBALA</option>
<option value="SPREF354">KOUN FAO</option>
<option value="SPREF316">KOUNAHIRI</option>
<option value="SPREF276">KOUTO</option>
<option value="SPREF184">KPATA</option>
<option value="SPREF126">KPOUEBO</option>
<option value="SPREF115">KREGBE</option>
<option value="SPREF396">LA HAYE</option>
<option value="SPREF088">LAKOTA</option>
<option value="SPREF300">LANGUIBONOU</option>
<option value="SPREF346">LAOUDI BA</option>
<option value="SPREF483">LATAHA</option>
<option value="SPREF093">LAUZOUA</option>
<option value="SPREF387">LE CAIRE</option>
<option value="SPREF393">LIBREVILLE</option>
<option value="SPREF005">LILIYO</option>
<option value="SPREF173">LOGOUALE</option>
<option value="SPREF371">LOLOBO</option>
<option value="SPREF420">LOME</option>
<option value="SPREF120">LOMOKANKRO</option>
<option value="SPREF409">LONDRES</option>
<option value="SPREF165">LOPOU</option>
<option value="SPREF134">LOVIGUIE</option>
<option value="SPREF375">LUANDA</option>
<option value="SPREF099">M'BAHIAKRO</option>
<option value="SPREF111">M'BATTO</option>
<option value="SPREF255">M'BENGUE</option>
<option value="SPREF068">MADINANI</option>
<option value="SPREF388">MADRID</option>
<option value="SPREF043">MAFERE</option>
<option value="SPREF060">MAHANDIANA SOKOURANI</option>
<option value="SPREF189">MAHAPLEU</option>
<option value="SPREF457">MAMINIGUI</option>
<option value="SPREF172">MAN</option>
<option value="SPREF309">MANKONO</option>
<option value="SPREF466">MARABADJASSA</option>
<option value="SPREF313">MARHANDALLAH</option>
<option value="SPREF328">MASSALA</option>
<option value="SPREF004">MEAGUI</option>
<option value="SPREF444">MEKRO</option>
<option value="SPREF200">MEO</option>
<option value="SPREF406">MEXICO CITY</option>
<option value="SPREF418">MILAN</option>
<option value="SPREF055">MINIGNAN</option>
<option value="SPREF121">MOLONOU</option>
<option value="SPREF129">MOLONOU BLE</option>
<option value="SPREF402">MONROVIA</option>
<option value="SPREF144">MOROKRO</option>
<option value="SPREF332">MORONDO</option>
<option value="SPREF410">MOSCOU</option>
<option value="SPREF430">M?BENGUE</option>
<option value="SPREF415">N'DJAMENA</option>
<option value="SPREF142">N'DOUCI</option>
<option value="SPREF460">N'GANON</option>
<option value="SPREF070">N'GOLOBLASSO</option>
<option value="SPREF118">N'GUESSANKRO</option>
<option value="SPREF110">N'ZECREZESSOU</option>
<option value="SPREF468">NAFANA (KONG)</option>
<option value="SPREF439">NAFANA (PRIKRO)</option>
<option value="SPREF227">NAHIO</option>
<option value="SPREF228">NAMANE</option>
<option value="SPREF249">NAPIELEDOUGOU</option>
<option value="SPREF337">NASSIAN</option>
<option value="SPREF397">NEW DELHI</option>
<option value="SPREF390">NEW-YORK</option>
<option value="SPREF028">NIABLE</option>
<option value="SPREF290">NIAKARAMADOUGOU</option>
<option value="SPREF090">NIAMBEZARIA</option>
<option value="SPREF216">NIDROU</option>
<option value="SPREF292">NIEDEKAHA</option>
<option value="SPREF267">NIELLE</option>
<option value="SPREF465">NIEMENE</option>
<option value="SPREF252">NIOFOIN</option>
<option value="SPREF053">NOE</option>
<option value="SPREF105">NOFOU</option>
<option value="SPREF054">NOUAMOU</option>
<option value="SPREF061">ODIENNE</option>
<option value="SPREF154">OGHLWAPO</option>
<option value="SPREF086">OGOUGOU</option>
<option value="SPREF006">OKROUYO</option>
<option value="SPREF018">OLODIO</option>
<option value="SPREF133">ORESS KROBOU</option>
<option value="SPREF383">OTTAWA</option>
<option value="SPREF381">OUAGADOUGOU</option>
<option value="SPREF265">OUANGOLODOUGOU</option>
<option value="SPREF324">OUANINOU</option>
<option value="SPREF098">OUELLE</option>
<option value="SPREF080">OUME</option>
<option value="SPREF007">OUPOYO</option>
<option value="SPREF074">OURAGAHIO</option>
<option value="SPREF219">OUYABLY GNANDROU</option>
<option value="SPREF140">PACCOBO</option>
<option value="SPREF455">PAKOUABO</option>
<option value="SPREF392">PARIS</option>
<option value="SPREF198">PEHE</option>
<option value="SPREF384">PEKIN</option>
<option value="SPREF472">PINDA-BOROKO</option>
<option value="SPREF176">PODIAGOUINE</option>
<option value="SPREF419">PRETORIA</option>
<option value="SPREF101">PRIKRO</option>
<option value="SPREF405">RABAT</option>
<option value="SPREF438">RAVIART</option>
<option value="SPREF376">RIYADH</option>
<option value="SPREF400">ROME</option>
<option value="SPREF136">RUBINO</option>
<option value="SPREF021">SAGO</option>
<option value="SPREF229">SAIOUA</option>
<option value="SPREF306">SAKASSOU</option>
<option value="SPREF065">SAMANGO</option>
<option value="SPREF071">SAMATIGUILA</option>
<option value="SPREF010">SAN PEDRO</option>
<option value="SPREF351">SANDEGUE</option>
<option value="SPREF442">SANDOUGOU-SOBA</option>
<option value="SPREF174">SANGOUINE</option>
<option value="SPREF185">SANTA</option>
<option value="SPREF348">SAPLI SEPINGO</option>
<option value="SPREF315">SARHALA</option>
<option value="SPREF019">SASSANDRA</option>
<option value="SPREF288">SATAMA SOKORO</option>
<option value="SPREF289">SATAMA SOKOURA</option>
<option value="SPREF484">SEDIOGO</option>
<option value="SPREF326">SEGUELA</option>
<option value="SPREF069">SEGUELON</option>
<option value="SPREF448">SEILEU</option>
<option value="SPREF234">SEITIFLA</option>
<option value="SPREF217">SEMIEN</option>
<option value="SPREF385">SEOUL</option>
<option value="SPREF077">SERIHIO</option>
<option value="SPREF064">SEYDOUGOU</option>
<option value="SPREF280">SIANHALA</option>
<option value="SPREF272">SIEMPURGO</option>
<option value="SPREF329">SIFIE</option>
<option value="SPREF145">SIKENSI</option>
<option value="SPREF485">SIKOLO</option>
<option value="SPREF257">SINEMATIALI</option>
<option value="SPREF241">SINFRA</option>
<option value="SPREF183">SIPILOU</option>
<option value="SPREF256">SIRASSO</option>
<option value="SPREF459">SOHOUO</option>
<option value="SPREF464">SOKOLA-SOBARA</option>
<option value="SPREF057">SOKORO</option>
<option value="SPREF339">SOMINASSE</option>
<option value="SPREF366">SONGON</option>
<option value="SPREF347">SOROBANGO</option>
<option value="SPREF001">SOUBRE</option>
<option value="SPREF141">TAABO</option>
<option value="SPREF350">TABAGNE</option>
<option value="SPREF015">TABOU</option>
<option value="SPREF293">TAFIRE</option>
<option value="SPREF193">TAI</option>
<option value="SPREF361">TANDA</option>
<option value="SPREF035">TANGUELAN</option>
<option value="SPREF357">TANKESSE</option>
<option value="SPREF349">TAOUDI</option>
<option value="SPREF179">TEAPLEU</option>
<option value="SPREF363">TEDIO</option>
<option value="SPREF398">TEHERAN</option>
<option value="SPREF340">TEHINI</option>
<option value="SPREF399">TEL-AVIV</option>
<option value="SPREF273">TENGRELA</option>
<option value="SPREF052">TIAPOUM</option>
<option value="SPREF139">TIASSALE</option>
<option value="SPREF456">TIBEITA</option>
<option value="SPREF130">TIE N'DIEKRO</option>
<option value="SPREF119">TIEBISSOU</option>
<option value="SPREF063">TIEME</option>
<option value="SPREF113">TIEMELEKRO</option>
<option value="SPREF314">TIENINGBOUE</option>
<option value="SPREF056">TIENKO</option>
<option value="SPREF358">TIENKOIKRO</option>
<option value="SPREF454">TIENY-SIABLY</option>
<option value="SPREF283">TIMBE</option>
<option value="SPREF199">TIOBLY</option>
<option value="SPREF253">TIORONIARADOUGOU</option>
<option value="SPREF264">TOGONIERE</option>
<option value="SPREF401">TOKYO</option>
<option value="SPREF479">TOMORA</option>
<option value="SPREF081">TONLA</option>
<option value="SPREF294">TORTIYA</option>
<option value="SPREF218">TOTRODROU</option>
<option value="SPREF318">TOUBA</option>
<option value="SPREF341">TOUGBO</option>
<option value="SPREF197">TOULEPLEU</option>
<option value="SPREF123">TOUMODI</option>
<option value="SPREF308">TOUMODI SAKASSOU</option>
<option value="SPREF268">TOUMOUKORO</option>
<option value="SPREF164">TOUPAH</option>
<option value="SPREF359">TRANSUA</option>
<option value="SPREF403">TRIPOLI</option>
<option value="SPREF416">TUNIS</option>
<option value="SPREF411">VATICAN</option>
<option value="SPREF232">VAVOUA</option>
<option value="SPREF378">VIENNE</option>
<option value="SPREF247">VOUEBOUFLA</option>
<option value="SPREF389">WASHINGTON</option>
<option value="SPREF330">WOROFLA</option>
<option value="SPREF160">YAKASSE ATTOBROU</option>
<option value="SPREF030">YAKASSE FEYASSE</option>
<option value="SPREF152">YAKASSE ME</option>
<option value="SPREF122">YAKPABO SAKASSOU</option>
<option value="SPREF368">YAMOUSSOUKRO</option>
<option value="SPREF045">YAOU</option>
<option value="SPREF382">YAOUNDE </option>
<option value="SPREF443">YAPLEU</option>
<option value="SPREF471">YEZIMALA</option>
<option value="SPREF094">YOCOBOUE</option>
<option value="SPREF352">YOROBODI</option>
<option value="SPREF446">YORODOUGOU</option>
<option value="SPREF222">ZAÏBO</option>
<option value="SPREF192">ZAGNE</option>
<option value="SPREF239">ZAGUIETA</option>
<option value="SPREF029">ZARANOU</option>
<option value="SPREF196">ZEAGLO</option>
<option value="SPREF209">ZEO</option>
<option value="SPREF089">ZIKISSO</option>
<option value="SPREF208">ZOU</option>
<option value="SPREF178">ZOUAN HOUNIEN</option>
<option value="SPREF235">ZOUKOUGBEU</option>
<option value="SPREF245">ZUENOULA</option>